version: 2
jobs:
    build-ubuntu:
        docker:
            - image: ubuntu:rolling
            - image: cassandra:latest
              environment:
                CASSANDRA_LISTEN_ADDRESS: auto
                CASSANDRA_RPC_ADDRESS: localhost
                CASSANDRA_CLUSTER_NAME: priam_cassandra_cluster
                CASSANDRA_DC: priam_cassandra_dc
                MAX_HEAP_SIZE: 512m
                HEAP_NEWSIZE: 256m

        steps:
            - run:
                name: update
                command: apt-get -y update
            - run:
                name: install dependencies
                command: |
                    apt-get -y install \
                        git \
                        cmake \
                        ninja-build \
                        g++ \
                        clang \
                        zlib1g-dev \
                        libuv1-dev \
                        libssl-dev \
                        netcat
            - checkout
            - run:
                name: git init submodules
                command: |
                    git submodule update --init --recursive
            - run:
                name: build release g++
                command: |
                    mkdir build-release-g++
                    cd build-release-g++
                    cmake \
                        -GNinja \
                        -DCMAKE_BUILD_TYPE=Release \
                        -DCMAKE_C_COMPILER=gcc \
                        -DCMAKE_CXX_COMPILER=g++ \
                        ..
                    ninja -j1
            - run:
                name: build release clang++
                command: |
                    mkdir build-release-clang++
                    cd build-release-clang++
                    cmake \
                        -GNinja \
                        -DCMAKE_BUILD_TYPE=Release \
                        -DCMAKE_C_COMPILER=clang \
                        -DCMAKE_CXX_COMPILER=clang++ \
                        ..
                    ninja -j1
            - run:
                name: wait for cassandra to start
                command: |
                    for i in `seq 1 30`;
                    do
                        nc -z localhost 9042 && echo "Connected to cassandra." && exit 0
                        echo -n
                        sleep 1
                    done
                    echo Failed waiting for Cassandra && exit 1
            - run:
                name: test release g++
                command: |
                    cd build-release-g++
                    ctest -V
            - run:
                name: test release clang++
                command: |
                    cd build-release-clang++
                    ctest -V

    build-fedora:
        docker:
            - image: fedora:latest
            - image: cassandra:latest
              environment:
                CASSANDRA_LISTEN_ADDRESS: auto
                CASSANDRA_RPC_ADDRESS: localhost
                CASSANDRA_CLUSTER_NAME: priam_cassandra_cluster
                CASSANDRA_DC: priam_cassandra_dc
                MAX_HEAP_SIZE: 512m
                HEAP_NEWSIZE: 256m
        steps:
            - run:
                name: update
                command: dnf update -y
            - run:
                name: install dependencies
                command: |
                    dnf install -y \
                        git \
                        cmake \
                        ninja-build \
                        g++ \
                        clang \
                        zlib-devel \
                        libuv-devel \
                        openssl-devel \
                        nc
            - checkout
            - run:
                name: git init submodules
                command: |
                    git submodule update --init --recursive
            - run:
                name: build release g++
                command: |
                    mkdir build-release-g++
                    cd build-release-g++
                    cmake \
                        -GNinja \
                        -DCMAKE_BUILD_TYPE=Release \
                        -DCMAKE_C_COMPILER=gcc \
                        -DCMAKE_CXX_COMPILER=g++ \
                        ..
                    ninja -j1
            - run:
                name: build release clang++
                command: |
                    mkdir build-release-clang++
                    cd build-release-clang++
                    cmake \
                        -GNinja \
                        -DCMAKE_BUILD_TYPE=Release \
                        -DCMAKE_C_COMPILER=clang \
                        -DCMAKE_CXX_COMPILER=clang++ \
                        ..
                    ninja -j1
            - run:
                name: wait for cassandra to start
                command: |
                    for i in `seq 1 30`;
                    do
                        nc -z localhost 9042 && echo "Connected to cassandra." && exit 0
                        echo -n
                        sleep 1
                    done
                    echo Failed waiting for Cassandra && exit 1
            - run:
                name: test release g++
                command: |
                    cd build-release-g++
                    ctest -V
            - run:
                name: test release clang++
                command: |
                    cd build-release-clang++
                    ctest -V

workflows:
    version: 2
    build-test:
        jobs:
        - build-ubuntu
        # the OSS/free tier can't handle them all at once
        - build-fedora:
            requires:
                - build-ubuntu
